name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: siddhantdixit/randomAssignBOT
              with:
                  repo-token: ${{ github.token }}
                  assignees: siddhantdixit,twentythreeapril
