name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: siddhantdixit/auto-assign-issue@v2.3
              with:
                  assignees: siddhantdixit,twentythreeapril
